"use client";
// File: src/components/dashboard/views/DiscrepancyView.tsx

import React, { useMemo, useState, useEffect } from 'react';
import { ComposedChart, Bar, Scatter, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Cell } from 'recharts';
import type { DigitalIDAssessmentOutput } from '@/types/scoring';
import type { RawAssessmentSession, RawAssessmentResponse } from '@/lib/assessmentAggregation';
import { frameworkQuestions, type FrameworkQuestion } from '@/data/frameworkQuestions';
import { Users2, AlertTriangle, CheckCircle2, EyeOff, Info, Lightbulb, TrendingDown, TrendingUp, Target } from 'lucide-react';

interface Props {
  result: DigitalIDAssessmentOutput | null;
  sessions: RawAssessmentSession[];
  responses: RawAssessmentResponse[];
}

// Strictly type the data generated by our engine so tooltips and ticks never throw TS errors
interface DiscrepancyData {
  code: string;
  name: string;
  pillarCode: string;
  pillarName: string;
  gap: number;
  expert: number;
  survey: number;
  lineData: number[];
}

const MATURITY_LABELS = ['Basic', 'Opportunistic', 'Systematic', 'Differentiating', 'Transformational'];

// Sanitized SVG Shape for the Dots without using 'any'
const CleanDot = (props: { cx?: number; cy?: number; fill?: string }) => {
  const { cx, cy, fill } = props;
  if (typeof cx !== 'number' || typeof cy !== 'number') return null;
  return <circle cx={cx} cy={cy} r={6} fill={fill} className="shadow-sm" />;
};

// FIXED ALIGNMENT & TYPING: Strict payload typing instead of 'any'
const CustomXAxisTick = ({ x, y, payload }: { x?: number; y?: number; payload?: { value: number } }) => {
  if (payload?.value === undefined) return null;
  const label = MATURITY_LABELS[payload.value - 1] || String(payload.value);
  return (
    <g transform={`translate(${x},${y})`}>
      <text
        x={0}
        y={0}
        dx={-10}
        dy={15}
        textAnchor="end"
        fill="#8A95A3"
        fontSize={10}
        fontWeight={800}
        transform="rotate(-35)"
        className="uppercase tracking-widest"
      >
        {label}
      </text>
    </g>
  );
};

export default function DiscrepancyView({ result, sessions, responses }: Props) {
  // 1. Strict Hydration Guard to prevent Next.js SSR -1 / NaN Recharts crash
  const [isMounted, setIsMounted] = useState(false);
  useEffect(() => {
    const timer = setTimeout(() => setIsMounted(true), 100);
    return () => clearTimeout(timer);
  }, []);

  // 2. React Hooks ordering requirement: ALL hooks must execute before the early return

  const { expertCount, stakeholderCount, totalCount } = useMemo(() => {
    if (!sessions || !responses) return { expertCount: 0, stakeholderCount: 0, totalCount: 0 };
    const activeSessionIds = Array.from(new Set(responses.map(r => r.assessment_id)));
    let experts = 0; let stakeholders = 0;
    activeSessionIds.forEach(id => {
      const s = sessions.find(session => session.id === id);
      if (s?.survey_type === 'expert') experts++;
      if (s?.survey_type === 'stakeholder') stakeholders++;
    });
    return { expertCount: experts, stakeholderCount: stakeholders, totalCount: experts + stakeholders };
  }, [sessions, responses]);

  const pillarMap = useMemo(() => {
    const map = new Map<string, string>();
    frameworkQuestions.forEach((q: FrameworkQuestion) => map.set(q.pillar_code, q.pillar_name));
    return map;
  }, []);

  const subpillars = useMemo(() => result?.subpillars || [], [result]);

  const data: DiscrepancyData[] = useMemo(() => {
    return subpillars
      .filter((sp) => {
        if (sp.expert_mean == null || sp.survey_mean == null) return false;
        return !isNaN(Number(sp.expert_mean)) && !isNaN(Number(sp.survey_mean));
      })
      .map((sp) => {
        const pCode = sp.code.split('.')[0];
        const exp = Number(sp.expert_mean);
        const sur = Number(sp.survey_mean);
        return {
          code: sp.code,
          name: sp.name,
          pillarCode: pCode,
          pillarName: pillarMap.get(pCode) || `Pillar ${pCode}`,
          gap: Number((exp - sur).toFixed(2)),
          expert: exp,
          survey: sur,
          lineData: [Math.min(exp, sur), Math.max(exp, sur)],
        };
      })
      .sort((a, b) => a.code.localeCompare(b.code));
  }, [subpillars, pillarMap]);

  const insights = useMemo(() => {
    if (data.length === 0) return null;
    const riskBlindspot = [...data].sort((a, b) => a.gap - b.gap)[0];
    const deliveryGap = [...data].sort((a, b) => b.gap - a.gap)[0];
    const strongestConsensus = [...data].sort((a, b) => Math.abs(a.gap) - Math.abs(b.gap))[0];
    return { riskBlindspot, deliveryGap, strongestConsensus };
  }, [data]);

  // 3. SAFE EARLY RETURN: Placed perfectly after all hooks to clear lint errors
  if (!result) return <Empty />;

  // Derived Metrics
  const flagged = data.filter((d) => Math.abs(d.gap) >= 1.0);
  const highConsensus = data.filter((d) => Math.abs(d.gap) <= 0.5).length;
  const blindSpots = subpillars.filter(t => t.expert_mean == null || t.survey_mean == null).length;

  const rowHeight = 60;
  const chartHeight = Math.max(500, data.length * rowHeight);
  const marginTop = 20;
  const marginBottom = 100;
  const drawHeight = chartHeight - marginTop - marginBottom;
  const bandSize = data.length > 0 ? drawHeight / data.length : 0;

  // Embedded component strictly typed, pulling from the memoized 'data'
  const CustomLeftTick = ({ x, y, payload }: { x?: number; y?: number; payload?: { value: string } }) => {
    const item = data.find(d => d.code === payload?.value);
    if (!item) return null;
    return (
      <g transform={`translate(${x},${y})`}>
        <text x={-16} y={-6} textAnchor="end" fill="#8A95A3" fontSize={9} fontWeight={800} className="uppercase tracking-widest">
          {item.pillarCode} - {item.pillarName}
        </text>
        <text x={-16} y={8} textAnchor="end" fill="#0D1117" fontSize={11} fontWeight={700}>
          {item.code}: {item.name}
        </text>
      </g>
    );
  };

  return (
    <div className="space-y-8 font-sans max-w-[1600px] mx-auto pb-12">

      {/* Executive Summary Bar */}
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6">
        <StatCard icon={<Users2 />} label="Active Participants" value={String(totalCount)} subtext={`${expertCount} Experts • ${stakeholderCount} Stakeholders`} color="#003DA5" />
        <StatCard icon={<AlertTriangle />} label="Critical Disagreements" value={String(flagged.length)} subtext="Scoring gap of 1.0 or higher" color="#C53030" />
        <StatCard icon={<CheckCircle2 />} label="Strong Consensus" value={String(highConsensus)} subtext="Scores within 0.5 difference" color="#059669" />
        <StatCard icon={<EyeOff />} label="Incomplete Data" value={String(blindSpots)} subtext="Topics missing one perspective" color="#8A95A3" />
      </div>

      {/* Strategic Narrative Block */}
      {insights && (
        <div className="bg-white border border-[#003DA5]/20 rounded-3xl p-8 shadow-sm">
          <div className="flex items-center gap-3 mb-6 border-b border-[#F1F5F9] pb-4">
            <Lightbulb className="w-5 h-5 text-[#003DA5]" />
            <h4 className="text-sm font-black text-[#0D1117] uppercase tracking-widest">Expert vs. Stakeholder Insights</h4>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
            <InsightRow title="Hidden Risk (Expert Warning)" color="text-[#C53030]" icon={<TrendingDown className="w-4 h-4" />}>
              Stakeholders are optimistic about <span className="font-bold">{insights.riskBlindspot.code}</span> ({insights.riskBlindspot.survey.toFixed(1)}), but experts rate it lower ({insights.riskBlindspot.expert.toFixed(1)}). This suggests potential structural vulnerabilities.
            </InsightRow>
            <InsightRow title="User Friction (Delivery Gap)" color="text-[#B7791F]" icon={<TrendingUp className="w-4 h-4" />}>
              Experts rate <span className="font-bold">{insights.deliveryGap.code}</span> highly ({insights.deliveryGap.expert.toFixed(1)}), yet users experience it poorly ({insights.deliveryGap.survey.toFixed(1)}). The policy is not reaching the end-user.
            </InsightRow>
            <InsightRow title="Maturity Anchor (Alignment)" color="text-[#059669]" icon={<Target className="w-4 h-4" />}>
              Both groups agree precisely on <span className="font-bold">{insights.strongestConsensus.code}</span> (~{insights.strongestConsensus.expert.toFixed(1)}), providing your most stable maturity baseline.
            </InsightRow>
          </div>
        </div>
      )}

      {/* The Dumbbell Alignment Map */}
      <div className="bg-white border border-[#DDE1E9] rounded-3xl p-8 shadow-sm">
        <div className="flex flex-col lg:flex-row lg:items-start justify-between mb-8 gap-4 relative">
          <div>
            <h3 className="text-xl font-black text-[#0D1117] font-display mb-1">Expert vs. Stakeholder Perspective Variance</h3>
            <p className="text-[10px] text-[#8A95A3] font-black uppercase tracking-[0.2em] flex items-center gap-2">
              <Info className="w-3.5 h-3.5" /> Comparing the scoring discrepancy between expert assessments and stakeholder perspectives.
            </p>
          </div>
          <LegendBlock />
        </div>

        <div className="w-full relative">
          <TableHeaderOverlay />
          <div className="absolute top-[40px] right-0 w-[240px] pointer-events-none z-10" style={{ height: chartHeight }}>
            {data.map((item, index) => {
              const centerY = marginTop + (index * bandSize) + (bandSize / 2);
              return (
                <div key={item.code} className="absolute w-full flex items-center justify-between pr-4 -translate-y-1/2" style={{ top: centerY }}>
                  <span className="w-[60px] text-center text-[#003DA5] font-black text-xs">{item.expert.toFixed(2)}</span>
                  <span className="w-[80px] text-center text-[#8A95A3] font-black text-xs">{item.survey.toFixed(2)}</span>
                  <span className={`w-[60px] text-center font-black text-xs ${Math.abs(item.gap) >= 1.0 ? 'text-[#C53030]' : 'text-[#4A5568]'}`}>
                    {item.gap > 0 ? '+' : ''}{item.gap.toFixed(2)}
                  </span>
                </div>
              );
            })}
          </div>

          <div className="pt-[40px]">
            {isMounted ? (
              // Recharts protection deployed with minHeight/minWidth
              <ResponsiveContainer width="100%" height={chartHeight} minHeight={100} minWidth={100}>
                <ComposedChart layout="vertical" data={data} margin={{ top: marginTop, right: 240, left: 0, bottom: marginBottom }}>
                  <CartesianGrid strokeDasharray="3 3" horizontal={true} vertical={false} stroke="#F1F5F9" />

                  <XAxis
                    type="number"
                    domain={[0.5, 5.5]}
                    ticks={[1, 2, 3, 4, 5]}
                    interval={0}
                    tick={<CustomXAxisTick />}
                    height={marginBottom}
                    axisLine={{ stroke: '#DDE1E9' }}
                    tickLine={false}
                  />

                  <YAxis yAxisId="left" type="category" dataKey="code" width={320} tick={<CustomLeftTick />} axisLine={false} tickLine={false} />
                  <YAxis yAxisId="right" orientation="right" type="category" dataKey="code" width={240} tick={false} axisLine={false} tickLine={false} />

                  <Tooltip cursor={{ fill: 'rgba(0,61,165,0.03)' }} content={<CustomTooltip />} />

                  <Bar yAxisId="left" dataKey="lineData" barSize={4} radius={2}>
                    {data.map((entry, index) => (
                      <Cell key={index} fill={Math.abs(entry.gap) >= 1.0 ? '#FEB2B2' : '#E2E8F0'} />
                    ))}
                  </Bar>

                  <Scatter yAxisId="left" dataKey="expert" fill="#003DA5" shape={<CleanDot />} />
                  <Scatter yAxisId="left" dataKey="survey" fill="#8A95A3" shape={<CleanDot />} />
                </ComposedChart>
              </ResponsiveContainer>
            ) : <div style={{ height: chartHeight }} className="flex items-center justify-center bg-[#F8FAFC]">Loading Map...</div>}
          </div>
        </div>
      </div>
    </div>
  );
}

// 4. Helper Components strictly typed to eliminate '@typescript-eslint/no-explicit-any'
function StatCard({ icon, label, value, subtext, color }: { icon: React.ReactNode; label: string; value: string; subtext: string; color: string }) {
  return (
    <div className="bg-white border border-[#DDE1E9] rounded-[2.5rem] p-8 flex flex-col justify-center shadow-sm">
      <div className="flex items-center gap-5 mb-4">
        <div className="w-12 h-12 rounded-2xl flex items-center justify-center text-white" style={{ backgroundColor: color }}>{icon}</div>
        <span className="text-4xl font-black text-[#0D1117] font-display">{value}</span>
      </div>
      <span className="text-[11px] font-black uppercase tracking-widest text-[#0D1117] mb-1">{label}</span>
      <span className="text-[10px] font-bold text-[#64748B]">{subtext}</span>
    </div>
  );
}

function InsightRow({ title, color, icon, children }: { title: string; color: string; icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <div className="space-y-2">
      <div className={`flex items-center gap-2 ${color}`}>
        {icon} <span className="text-[10px] font-black uppercase tracking-wider">{title}</span>
      </div>
      <p className="text-sm text-[#4A5568] leading-relaxed">{children}</p>
    </div>
  );
}

function LegendBlock() {
  return (
    <div className="flex items-center gap-6 bg-[#F8F9FB] px-6 py-4 rounded-2xl border border-[#DDE1E9] text-[11px] font-black uppercase tracking-widest text-[#4A5568]">
      <div className="flex items-center gap-2">
        <div className="w-3 h-3 rounded-full bg-[#003DA5]"></div> <span>Expert Mean</span>
      </div>
      <div className="w-px h-4 bg-[#DDE1E9]"></div>
      <div className="flex items-center gap-2">
        <div className="w-3 h-3 rounded-full bg-[#8A95A3]"></div> <span>Stakeholder Mean</span>
      </div>
    </div>
  );
}

function TableHeaderOverlay() {
  return (
    <div className="absolute top-0 right-0 w-[240px] h-[40px] flex items-end justify-between pr-4 pb-2 border-b border-[#DDE1E9] bg-white z-10">
      <span className="w-[60px] text-center text-[9px] font-black text-[#8A95A3] uppercase">Expert<br />Mean</span>
      <span className="w-[80px] text-center text-[9px] font-black text-[#8A95A3] uppercase">Stakeholder<br />Mean</span>
      <span className="w-[60px] text-center text-[9px] font-black text-[#8A95A3] uppercase">Scoring<br />Gap</span>
    </div>
  );
}

const CustomTooltip = ({ active, payload }: { active?: boolean; payload?: Array<{ payload: DiscrepancyData }> }) => {
  if (active && payload?.[0]) {
    const d = payload[0].payload;
    return (
      <div className="bg-white border border-[#DDE1E9] rounded-2xl shadow-xl p-4 text-xs font-sans min-w-[200px]">
        <span className="font-bold text-[#8A95A3] uppercase text-[9px]">{d.pillarName}</span>
        <div className="grid grid-cols-2 gap-4 mt-2">
          <div><p className="text-[#4A5568]">Expert:</p> <p className="font-black text-[#003DA5]">{d.expert.toFixed(2)}</p></div>
          <div><p className="text-[#4A5568]">Stakeholder:</p> <p className="font-black text-[#8A95A3]">{d.survey.toFixed(2)}</p></div>
          <div className="col-span-2 border-t pt-2"><p className="text-[#C53030]">Gap:</p> <p className="font-black text-[#C53030]">{d.gap > 0 ? '+' : ''}{d.gap.toFixed(2)}</p></div>
        </div>
      </div>
    );
  }
  return null;
};

function Empty() {
  return <div className="py-24 text-center border rounded-3xl">Index Missing. Execute scoring to generate divergence.</div>;
}