/* eslint-disable */
const fs = require('fs');
const content = fs.readFileSync('src/data/frameworkQuestions.ts', 'utf8');
const rubric = JSON.parse(fs.readFileSync('src/config/rubric_config.json', 'utf8'));

// Extract all q_codes from frameworkQuestions
const qCodeMatches = Array.from(content.matchAll(/"q_code"\s*:\s*"([^"]+)"/g));
const fqCodes = new Set(qCodeMatches.map(m => m[1]));

// Build a map of subpillar -> {EX: [], NE: []} from frameworkQuestions
const spMap = {};
for (const code of fqCodes) {
    const parts = code.split('.');
    if (parts.length < 4) continue;
    const sp = parts[0] + '.' + parts[1];
    const type = parts[2]; // EX or NE
    if (!spMap[sp]) spMap[sp] = { EX: [], NE: [] };
    if (type === 'EX') spMap[sp].EX.push(code);
    else if (type === 'NE') spMap[sp].NE.push(code);
}

// Build rubric map
const rubricSubpillars = rubric.subpillars;
const rubricQCodes = new Set();
const issues = [];

console.log('=== RUBRIC vs FRAMEWORK QUESTIONS COMPARISON ===');
for (const [spCode, spConfig] of Object.entries(rubricSubpillars)) {
    const rubricEX = [];
    const rubricNE = [];
    const rubricIND = [];
    for (const [qCode, qConf] of Object.entries(spConfig.questions)) {
        rubricQCodes.add(qCode);
        if (qConf.component === 'expert') rubricEX.push(qCode);
        else if (qConf.component === 'survey') rubricNE.push(qCode);
        else if (qConf.component === 'indicator') rubricIND.push(qCode);
    }

    const fqEX = (spMap[spCode] && spMap[spCode].EX) || [];
    const fqNE = (spMap[spCode] && spMap[spCode].NE) || [];

    const rubricEXStr = rubricEX.map(c => c.split('.').slice(2).join('.')).sort().join(',');
    const fqEXStr = fqEX.map(c => c.split('.').slice(2).join('.')).sort().join(',');
    const rubricNEStr = rubricNE.map(c => c.split('.').slice(2).join('.')).sort().join(',');
    const fqNEStr = fqNE.map(c => c.split('.').slice(2).join('.')).sort().join(',');

    const exMatch = rubricEXStr === fqEXStr;
    const neMatch = rubricNEStr === fqNEStr;

    if (!exMatch || !neMatch) {
        console.log('\nSUBPILLAR: ' + spCode);
        if (!exMatch) {
            console.log('  EX - Rubric: [' + rubricEX.join(', ') + '] | FQ: [' + fqEX.join(', ') + '] MISMATCH!');
            issues.push({ sp: spCode, type: 'EX', rubric: rubricEX, fq: fqEX });
        }
        if (!neMatch) {
            console.log('  NE - Rubric: [' + rubricNE.join(', ') + '] | FQ: [' + fqNE.join(', ') + '] MISMATCH!');
            issues.push({ sp: spCode, type: 'NE', rubric: rubricNE, fq: fqNE });
        }
    } else {
        console.log(spCode + ': OK (EX:' + rubricEX.length + ' NE:' + rubricNE.length + ' IND:' + rubricIND.length + ')');
    }
}

// Check for q_codes in rubric not in FQ
console.log('\n=== RUBRIC SURVEY/EXPERT CODES MISSING FROM FRAMEWORK QUESTIONS ===');
let missingCount = 0;
for (const [spCode, spConfig] of Object.entries(rubricSubpillars)) {
    for (const [qCode, qConf] of Object.entries(spConfig.questions)) {
        if (qConf.component !== 'indicator' && !fqCodes.has(qCode)) {
            console.log('MISSING from FQ: ' + qCode + ' (component: ' + qConf.component + ', weight: ' + qConf.weight + ')');
            missingCount++;
        }
    }
}
if (missingCount === 0) console.log('None - all rubric survey/expert codes found in FQ');

// Check for q_codes in FQ not in rubric
console.log('\n=== FRAMEWORK QUESTION Q-CODES NOT IN RUBRIC (orphans - wont be scored) ===');
let orphanCount = 0;
for (const code of fqCodes) {
    if (!rubricQCodes.has(code)) {
        console.log('ORPHAN: ' + code);
        orphanCount++;
    }
}
if (orphanCount === 0) console.log('None');

// Check indicator code alignment
console.log('\n=== INDICATOR CODES: RUBRIC vs indicators_master.csv ===');
const csvContent = fs.readFileSync('src/config/indicators_master.csv', 'utf8');
const csvLines = csvContent.split(/\r?\n/).slice(1);
let csvSubpillarCounter = {};
let csvCurrentSubpillar = '';
const csvIndicatorCodes = [];

for (const line of csvLines) {
    if (!line.trim()) continue;
    const cols = line.split(',');
    const subpillarCol = cols[2] && cols[2].trim();
    if (subpillarCol) {
        csvCurrentSubpillar = subpillarCol;
        if (!csvSubpillarCounter[csvCurrentSubpillar]) csvSubpillarCounter[csvCurrentSubpillar] = 0;
    }
    const descCol = cols[6] && cols[6].trim();
    if (!descCol || descCol === '') continue;
    csvSubpillarCounter[csvCurrentSubpillar]++;
    csvIndicatorCodes.push(csvCurrentSubpillar + '.' + csvSubpillarCounter[csvCurrentSubpillar]);
}

console.log('\nCSV Indicator codes generated by indicatorRegistry.ts logic:');
console.log(csvIndicatorCodes.join(', '));

// Rubric indicator codes
const rubricIndicatorCodes = [];
for (const [spCode, spConfig] of Object.entries(rubricSubpillars)) {
    for (const [qCode, qConf] of Object.entries(spConfig.questions)) {
        if (qConf.component === 'indicator') rubricIndicatorCodes.push(qCode);
    }
}
console.log('\nRubric indicator codes (IND.Px.y.zz format):');
console.log(rubricIndicatorCodes.join(', '));

// Weight sum check
console.log('\n=== WEIGHT SUM CHECK PER SUBPILLAR ===');
for (const [spCode, spConfig] of Object.entries(rubricSubpillars)) {
    let total = 0;
    for (const [qCode, qConf] of Object.entries(spConfig.questions)) {
        if (!qConf.zero_weight && qConf.weight > 0) total += qConf.weight;
    }
    const rounded = Math.round(total * 1000) / 1000;
    const ok = Math.abs(rounded - 1.0) < 0.005;
    if (!ok) console.log(spCode + ': WEIGHT SUM = ' + rounded + ' (PROBLEM!)');
    else console.log(spCode + ': weight sum = ' + rounded + ' OK');
}

console.log('\nTotal FQ q_codes: ' + fqCodes.size);
console.log('Total rubric q_codes: ' + rubricQCodes.size);
